SchoolTask.Views/Models/ErrorViewModel.cs
namespace SchoolTask.Views.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SchoolTask.Views/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolTask.Views.Models;
using System.Diagnostics;

namespace SchoolTask.Views.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SchoolTask.Views/Controllers/SchoolController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SchoolTaskModels.Dtos;
using System.Net;

namespace SchoolTask.Views.Controllers
{
    public class SchoolController : Controller
    {
        private HttpClient httpClient;
        private readonly string baseUrl = "https://localhost:44304/api/school";
        public SchoolController()
        {
            httpClient = new HttpClient();
        }

        // GET
        public async Task<IActionResult> Index()
        {
            using var result = await httpClient.GetAsync(baseUrl);
            var jsonSchoolsDtos = await result.Content.ReadAsStringAsync();

            IEnumerable<SchoolDto> schoolDtos = JsonConvert.DeserializeObject<List<SchoolDto>>(jsonSchoolsDtos);

            return View(schoolDtos);
        }

        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        public async Task<IActionResult> Create(CreateSchoolDto dto)
        {
            using var postResult = await httpClient.PostAsJsonAsync<CreateSchoolDto>(baseUrl, dto);
            
            if (postResult.StatusCode == HttpStatusCode.Created)
            {
                TempData["info"] = "School created successfully";
            }
            else
            {
                TempData["info"] = $"{postResult.StatusCode}";
            }

            return RedirectToAction("Index");
        }

        // GET
        public async Task<IActionResult> Delete(int id)
        {
            using var result = await httpClient.GetAsync(baseUrl + $"/{id}");
            var jsonSchoolDto = await result.Content.ReadAsStringAsync();

            if (jsonSchoolDto is null)
            {
                TempData["info"] = $"{result.StatusCode}";
                RedirectToAction("Index");
            }

            SchoolDto schoolDto = JsonConvert.DeserializeObject<SchoolDto>(jsonSchoolDto);

            return View(schoolDto);
        }

        // POST
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            using var deleteResult = await httpClient.DeleteAsync(baseUrl + $"/{id}");
            var statusCode = deleteResult.StatusCode;

            if (statusCode == HttpStatusCode.NoContent)
            {
                TempData["info"] = "School deleted successfully";
            }
            else
            {
                TempData["info"] = $"{statusCode}";
            }

            return RedirectToAction("Index");
        }

        // GET
        public async Task<IActionResult> Edit(int id)
        {
            using var result = await httpClient.GetAsync(baseUrl + $"/{id}");
            var jsonSchoolDto = await result.Content.ReadAsStringAsync();

            if (jsonSchoolDto is null)
            {
                TempData["info"] = $"{result.StatusCode}";
                RedirectToAction("Index");
            }

            SchoolDto schoolDto = JsonConvert.DeserializeObject<SchoolDto>(jsonSchoolDto);

            return View(schoolDto);
        }

        // POST
        [HttpPost]
        public async Task<IActionResult> Edit(SchoolDto dto)
        {
            UpdateSchoolDto updateDto = new()
            {
                FullName = dto.FullName,
                City = dto.City,
                Street = dto.Street
            };

            using var updateResult = await httpClient.PutAsJsonAsync<UpdateSchoolDto>(baseUrl + $"/{dto.Id}", updateDto);

            if (updateResult.StatusCode == HttpStatusCode.OK)
            {
                TempData["info"] = "School updated successfully";
            }
            else
            {
                TempData["info"] = $"{updateResult.StatusCode}";
            }

            return RedirectToAction("Index");
        }
    }
}

SchoolTask.Views/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SchoolTaskModels.Dtos;
using System.Net;

namespace SchoolTask.Views.Controllers
{
    public class StudentController : Controller
    {
        private HttpClient httpClient;
        private readonly string baseUrl = "https://localhost:44304/api/school";
        private int SchoolId;
        public StudentController()
        {
            httpClient = new HttpClient();
        }

        // GET
        public async Task<IActionResult> Index(int schoolId)
        {
            this.SchoolId = schoolId;
            using var result = await httpClient.GetAsync(baseUrl + $"/{schoolId}/student");
            var jsonStudentDtos = await result.Content.ReadAsStringAsync();

            IEnumerable<StudentDto> studentDtos = JsonConvert.DeserializeObject<List<StudentDto>>(jsonStudentDtos);

            return View(studentDtos);
        }

        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        public async Task<IActionResult> Create(CreateStudentDto dto)
        {
            using var postResult = await httpClient.PostAsJsonAsync<CreateStudentDto>(baseUrl + $"/{SchoolId}/student", dto);

            if (postResult.StatusCode == HttpStatusCode.Created)
            {
                TempData["info"] = "Student created successfully";
            }
            else
            {
                TempData["info"] = $"{postResult.StatusCode}";
            }

            return RedirectToAction("Index", SchoolId);
        }

    }
}

SchoolTask.Views/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SchoolTask.Views/Views/School/Create.cshtml
@using SchoolTaskModels.Dtos
@model CreateSchoolDto

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create School</h2>
            <hr />
        </div>

        <div asp-validation-summary="All"></div>

        <div class="mb-3">
            <label asp-for="FullName"></label>
            <input asp-for="FullName" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Street"></label>
            <input asp-for="Street" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Number"></label>
            <input asp-for="Number" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="SchoolType"></label>
            <input asp-for="SchoolType" class="form-control" />
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="School" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

SchoolTask.Views/Views/School/Delete.cshtml
@using SchoolTaskModels.Dtos
@model SchoolDto

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete School</h2>
            <hr />
        </div> 
         
        <div class="mb-3">
            <label asp-for="FullName"></label>
            <input asp-for="FullName" disabled class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" disabled class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Street"></label>
            <input asp-for="Street" disabled class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Number"></label>
            <input asp-for="Number" disabled class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="SchoolType"></label>
            <input asp-for="SchoolType" disabled class="form-control" />
        </div>

        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="School" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

SchoolTask.Views/Views/School/Edit.cshtml
@model SchoolTaskModels.Dtos.SchoolDto

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit School</h2>
            <hr />
        </div> 

         <div asp-validation-summary="All"></div>
         
        <div class="mb-3">
            <label asp-for="FullName"></label>
            <input asp-for="FullName" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Street"></label>
            <input asp-for="Street" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Number"></label>
            <input asp-for="Number" disabled class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="SchoolType"></label>
            <input asp-for="SchoolType" disabled class="form-control" />
        </div>

        <button type="submit" class="btn btn-warning" style="width:150px">Edit</button>
        <a asp-controller="School" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolTask.Views/Views/School/Index.cshtml
@using SchoolTaskModels.Dtos
@model IEnumerable<SchoolDto>
@{
    ViewData["Title"] = "Index";
}

@if(TempData["info"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.info('@TempData["info"]');
    </script>
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">School List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="School" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New School
            </a>
        </div>
    </div>
    <br />
    <br />

    <table class="table table-bordered table-striped" style="width:100%">

        <thead>

            <tr>
                <th>
                    FullName
                </th>
                <th>
                    City
                </th>
                <th>
                    Street
                </th>
                <th>
                    Number
                </th>
                <th>
                    SchoolType
                </th>
                <th></th>

            </tr>

        </thead>

        <tbody>

            @foreach (var school in Model)
            {
                <tr>
                    <td>
                        @school.FullName
                    </td>
                    <td>
                        @school.City
                    </td>
                    <td>
                        @school.Street
                    </td>
                    <td>
                        @school.Number
                    </td>
                    <td>
                        @school.SchoolType
                    </td>

                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="School" asp-action="Edit" asp-route-id="@school.Id" class="btn btn-primary mx-2"> 
                                <i class="bi bi-pencil-square"></i> Edit 
                            </a>

                            <a asp-controller="School" asp-action="Delete" asp-route-id="@school.Id" class="btn btn-danger mx-2"> 
                                <i class="bi bi-trash-fill"></i> Delete 
                            </a>

                            <a asp-controller="Student" asp-action="Index" asp-route-schoolId="@school.Id" class="btn btn-secondary mx-2"> 
                                <i class="bi bi-trash-fill"></i> Student 
                            </a>
                        </div>
                    </td>

                    @*@foreach (var student in school.Students)
                    {
                        <td>
                            <div>@student.Name | @student.Surname | @student.StudentIndex</div>
                        </td>
                    }*@

                </tr>
            }

        </tbody>

    </table>
</div>

SchoolTask.Views/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolTask.Views</title>
    <link rel="stylesheet" href="~/css/Minty.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolTask.Views.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="School" asp-action="Index">School</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SchoolTask.Views - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SchoolTask.Views/Views/Student/Create.cshtml
@using SchoolTaskModels.Dtos
@model CreateStudentDto

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Student</h2>
            <hr />
        </div>

        <div asp-validation-summary="All"></div>

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="Surname"></label>
            <input asp-for="Surname" class="form-control" />
        </div>

        <div class="mb-3">
            <label asp-for="StudentIndex"></label>
            <input asp-for="StudentIndex" class="form-control" />
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Student" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
@{
    <partial name="_ValidationScriptsPartial" />
}
}

SchoolTask.Views/Views/Student/Index.cshtml
@using SchoolTaskModels.Dtos
@model IEnumerable<StudentDto>
@{
    ViewData["Title"] = "Index";
}

@if (TempData["info"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.info('@TempData["info"]');
    </script>
}

<div class="container p-3">
    <div class="row">
        <div class="col-6" style="padding-left: 300px">
            <h2 class="text-primary">Student List</h2>
        </div>
        <div class="col-6" style="padding-left: 100px">
            <a asp-controller="School" asp-action="index" disabled class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Back to School List
            </a>
        </div>
    </div>
    <br />
    <br />

    <table class="table table-bordered table-striped" style="width:60%; margin-right:auto; margin-left:auto">

        <thead>

            <tr>
                <th>
                    Name
                </th>
                <th>
                    Surname
                </th>
                <th>
                    Student Index
                </th>

            </tr>

        </thead>

        <tbody>

            @foreach (var student in Model)
            {
                <tr>
                    <td>
                        @student.Name
                    </td>
                    <td>
                        @student.Surname
                    </td>
                    <td>
                        @student.StudentIndex
                    </td>

                </tr>
            }

        </tbody>

    </table>
</div>